import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Kazakhstan/Central Asia attractions with realistic coordinates
const attractionsData = [
  // Zone A: City Center (0-10km from Almaty center: 43.2220, 76.8512)
  {
    name: 'Panfilov Park',
    description: 'Central park with the famous Zenkov Cathedral',
    zone: 'A' as const,
    latitude: 43.2548,
    longitude: 76.9478,
    category: 'Cultural',
    city: 'Almaty',
    address: 'Gogol St 73, Almaty',
    estimatedDurationHours: 2,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800',
  },
  {
    name: 'Green Bazaar',
    description: 'Traditional market with local produce and crafts',
    zone: 'A' as const,
    latitude: 43.2578,
    longitude: 76.9432,
    category: 'Cultural',
    city: 'Almaty',
    address: '247 Zhibek Zholy Ave, Almaty',
    estimatedDurationHours: 2,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
  },
  {
    name: 'Kok Tobe',
    description: 'Mountain viewpoint with cable car and entertainment',
    zone: 'A' as const,
    latitude: 43.2308,
    longitude: 76.9653,
    category: 'Natural',
    city: 'Almaty',
    address: 'Kok Tobe Hill, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 15,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Republic Square',
    description: 'Main city square with monuments and fountains',
    zone: 'A' as const,
    latitude: 43.2366,
    longitude: 76.9457,
    category: 'Cultural',
    city: 'Almaty',
    address: 'Satpayev St, Almaty',
    estimatedDurationHours: 1,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
  },
  {
    name: 'Central State Museum',
    description: 'National museum showcasing Kazakhstan history',
    zone: 'A' as const,
    latitude: 43.2398,
    longitude: 76.9453,
    category: 'Historical',
    city: 'Almaty',
    address: '44 Samal-1, Almaty',
    estimatedDurationHours: 2,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1565883264935-f71023c9e6c9?w=800',
  },
  {
    name: 'Almaty Circus',
    description: 'Historic circus building with regular performances',
    zone: 'A' as const,
    latitude: 43.2507,
    longitude: 76.9289,
    category: 'Cultural',
    city: 'Almaty',
    address: '50 Abay Ave, Almaty',
    estimatedDurationHours: 2,
    basePriceImpact: 12,
    imageUrl: 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=800',
  },
  {
    name: 'Abay Opera House',
    description: 'Grand opera and ballet theater',
    zone: 'A' as const,
    latitude: 43.2408,
    longitude: 76.9492,
    category: 'Cultural',
    city: 'Almaty',
    address: '110 Kabanbay Batyr Ave, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 15,
    imageUrl: 'https://images.unsplash.com/photo-1580809361436-42a7ec204889?w=800',
  },
  {
    name: 'Arasan Baths',
    description: 'Traditional Turkish and Russian baths',
    zone: 'A' as const,
    latitude: 43.2511,
    longitude: 76.9512,
    category: 'Cultural',
    city: 'Almaty',
    address: '41 Tole Bi St, Almaty',
    estimatedDurationHours: 2,
    basePriceImpact: 12,
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800',
  },

  // Zone B: Suburban (10-50km from Almaty center)
  {
    name: 'Medeu Skating Rink',
    description: 'Famous high-altitude ice skating rink',
    zone: 'B' as const,
    latitude: 43.1639,
    longitude: 77.0694,
    category: 'Natural',
    city: 'Almaty',
    address: 'Medeu Valley, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 20,
    imageUrl: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800',
  },
  {
    name: 'Shymbulak Ski Resort',
    description: 'Premier ski resort in Tian Shan mountains',
    zone: 'B' as const,
    latitude: 43.1389,
    longitude: 77.0806,
    category: 'Natural',
    city: 'Almaty',
    address: 'Shymbulak, Almaty',
    estimatedDurationHours: 4,
    basePriceImpact: 25,
    imageUrl: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=800',
  },
  {
    name: 'Big Almaty Lake',
    description: 'Stunning turquoise alpine lake',
    zone: 'B' as const,
    latitude: 43.0558,
    longitude: 76.9900,
    category: 'Natural',
    city: 'Almaty',
    address: 'Big Almaty Lake, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 22,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Kok Zhailau',
    description: 'Mountain plateau with hiking trails',
    zone: 'B' as const,
    latitude: 43.1453,
    longitude: 77.0350,
    category: 'Natural',
    city: 'Almaty',
    address: 'Kok Zhailau Plateau, Almaty',
    estimatedDurationHours: 4,
    basePriceImpact: 20,
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
  },
  {
    name: 'Ile-Alatau National Park',
    description: 'Protected mountain park with diverse wildlife',
    zone: 'B' as const,
    latitude: 43.1117,
    longitude: 77.1119,
    category: 'Natural',
    city: 'Almaty',
    address: 'Ile-Alatau National Park, Almaty',
    estimatedDurationHours: 5,
    basePriceImpact: 25,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
  },
  {
    name: 'Falcon Nursery',
    description: 'Berkutchi falconry demonstration center',
    zone: 'B' as const,
    latitude: 43.1800,
    longitude: 76.7200,
    category: 'Cultural',
    city: 'Almaty',
    address: 'Falcon Nursery, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 20,
    imageUrl: 'https://images.unsplash.com/photo-1551244072-5d12893278ab?w=800',
  },
  {
    name: 'Turgen Gorge',
    description: 'Scenic gorge with waterfalls and hot springs',
    zone: 'B' as const,
    latitude: 43.2567,
    longitude: 77.2567,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Turgen Gorge, Almaty Region',
    estimatedDurationHours: 4,
    basePriceImpact: 25,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Issyk Lake',
    description: 'Mountain lake destroyed and rebuilt after mudslide',
    zone: 'B' as const,
    latitude: 43.2667,
    longitude: 77.4833,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Issyk, Almaty Region',
    estimatedDurationHours: 3,
    basePriceImpact: 22,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Tamgaly Tas',
    description: 'Ancient Buddhist rock carvings',
    zone: 'B' as const,
    latitude: 43.8258,
    longitude: 77.5636,
    category: 'Historical',
    city: 'Almaty Region',
    address: 'Tamgaly Tas, Almaty Region',
    estimatedDurationHours: 3,
    basePriceImpact: 22,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
  },
  {
    name: 'Altyn-Emel National Park Entry',
    description: 'Gateway to the singing dunes',
    zone: 'B' as const,
    latitude: 43.9417,
    longitude: 78.5333,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Altyn-Emel Entrance, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 20,
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
  },

  // Zone C: Regional (50-200km from Almaty)
  {
    name: 'Charyn Canyon',
    description: 'Spectacular red rock canyon formations',
    zone: 'C' as const,
    latitude: 43.3489,
    longitude: 79.0839,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Charyn Canyon, Almaty Region',
    estimatedDurationHours: 5,
    basePriceImpact: 50,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Kolsai Lakes',
    description: 'Three pristine mountain lakes',
    zone: 'C' as const,
    latitude: 42.9644,
    longitude: 78.3322,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Kolsai Lakes, Almaty Region',
    estimatedDurationHours: 6,
    basePriceImpact: 55,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Kaindy Lake',
    description: 'Submerged forest lake with standing trees',
    zone: 'C' as const,
    latitude: 42.9944,
    longitude: 78.4736,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Kaindy Lake, Almaty Region',
    estimatedDurationHours: 5,
    basePriceImpact: 52,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Altyn-Emel Singing Dunes',
    description: 'Sand dunes that produce musical sounds',
    zone: 'C' as const,
    latitude: 43.9222,
    longitude: 78.5889,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Singing Dunes, Altyn-Emel',
    estimatedDurationHours: 4,
    basePriceImpact: 50,
    imageUrl: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800',
  },
  {
    name: 'Aktau Mountains',
    description: 'Colorful white and red mountain formations',
    zone: 'C' as const,
    latitude: 43.8956,
    longitude: 78.7467,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Aktau Mountains, Altyn-Emel',
    estimatedDurationHours: 4,
    basePriceImpact: 50,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Besshatyr Burial Mounds',
    description: 'Ancient Saka royal burial complex',
    zone: 'C' as const,
    latitude: 43.5833,
    longitude: 77.8667,
    category: 'Historical',
    city: 'Almaty Region',
    address: 'Besshatyr, Almaty Region',
    estimatedDurationHours: 3,
    basePriceImpact: 45,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
  },
  {
    name: 'Saty Village',
    description: 'Traditional mountain village base for hiking',
    zone: 'C' as const,
    latitude: 42.8983,
    longitude: 78.3153,
    category: 'Cultural',
    city: 'Almaty Region',
    address: 'Saty Village, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 40,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
  },
  {
    name: 'Bartogay Reservoir',
    description: 'Large reservoir with water activities',
    zone: 'C' as const,
    latitude: 43.7253,
    longitude: 78.2667,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Bartogay, Almaty Region',
    estimatedDurationHours: 3,
    basePriceImpact: 42,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Kokpek Pass',
    description: 'Mountain pass with stunning views',
    zone: 'C' as const,
    latitude: 43.1500,
    longitude: 78.8500,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Kokpek Pass, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 40,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'Zharkent Mosque',
    description: 'Chinese-style wooden mosque',
    zone: 'C' as const,
    latitude: 44.1667,
    longitude: 80.0000,
    category: 'Historical',
    city: 'Zharkent',
    address: 'Zharkent, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 45,
    imageUrl: 'https://images.unsplash.com/photo-1564769610726-4b4d132eba3e?w=800',
  },

  // Additional Zone A attractions
  {
    name: '28 Panfilov Heroes Memorial',
    description: 'WWII memorial in Panfilov Park',
    zone: 'A' as const,
    latitude: 43.2560,
    longitude: 76.9490,
    category: 'Historical',
    city: 'Almaty',
    address: 'Panfilov Park, Almaty',
    estimatedDurationHours: 1,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1569163139394-de4798aa62b6?w=800',
  },
  {
    name: 'Zenkov Cathedral',
    description: 'Colorful wooden Orthodox cathedral',
    zone: 'A' as const,
    latitude: 43.2555,
    longitude: 76.9495,
    category: 'Historical',
    city: 'Almaty',
    address: 'Panfilov Park, Almaty',
    estimatedDurationHours: 1,
    basePriceImpact: 10,
    imageUrl: 'https://images.unsplash.com/photo-1580809361436-42a7ec204889?w=800',
  },
  {
    name: 'Almaty Zoo',
    description: 'City zoo with local and exotic animals',
    zone: 'A' as const,
    latitude: 43.2389,
    longitude: 76.8889,
    category: 'Cultural',
    city: 'Almaty',
    address: 'Yesenberlina St, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 12,
    imageUrl: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
  },
  {
    name: 'Fantasy World Amusement Park',
    description: 'Family amusement park with rides',
    zone: 'A' as const,
    latitude: 43.2125,
    longitude: 76.8653,
    category: 'Cultural',
    city: 'Almaty',
    address: 'Dostyk Ave, Almaty',
    estimatedDurationHours: 3,
    basePriceImpact: 15,
    imageUrl: 'https://images.unsplash.com/photo-1516815231560-8f41ec531527?w=800',
  },

  // Additional Zone B attractions
  {
    name: 'Tanbaly Petroglyphs',
    description: 'UNESCO World Heritage rock art site',
    zone: 'B' as const,
    latitude: 43.7250,
    longitude: 75.5944,
    category: 'Historical',
    city: 'Almaty Region',
    address: 'Tanbaly, Almaty Region',
    estimatedDurationHours: 3,
    basePriceImpact: 25,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
  },
  {
    name: 'Alakol Lake Shore',
    description: 'Salty lake with healing properties',
    zone: 'B' as const,
    latitude: 46.1000,
    longitude: 81.8000,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Alakol, Almaty Region',
    estimatedDurationHours: 4,
    basePriceImpact: 22,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },

  // Additional Zone C attractions
  {
    name: 'Kapchagai Reservoir',
    description: 'Large reservoir for water sports',
    zone: 'C' as const,
    latitude: 43.9000,
    longitude: 77.0667,
    category: 'Natural',
    city: 'Almaty Region',
    address: 'Kapchagai, Almaty Region',
    estimatedDurationHours: 4,
    basePriceImpact: 45,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  },
  {
    name: 'First President Park',
    description: 'Large park with monuments and gardens',
    zone: 'C' as const,
    latitude: 43.8500,
    longitude: 77.1000,
    category: 'Cultural',
    city: 'Almaty Region',
    address: 'First President Park, Almaty Region',
    estimatedDurationHours: 2,
    basePriceImpact: 40,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
  },
];

async function seedAttractions() {
  console.log('🎯 Starting attractions seed...');

  let created = 0;
  let skipped = 0;

  for (const attraction of attractionsData) {
    try {
      await prisma.attraction.upsert({
        where: {
          name: attraction.name,
        },
        update: {},
        create: {
          ...attraction,
        },
      });
      created++;
      console.log(`✅ Created: ${attraction.name} (Zone ${attraction.zone})`);
    } catch (error) {
      // If attraction already exists (unique constraint on name), skip it
      skipped++;
      console.log(`⏭️  Skipped: ${attraction.name} (already exists)`);
    }
  }

  console.log('\n🎉 Attractions seeded successfully!');
  console.log('\n📊 Summary:');
  console.log(`- Created: ${created}`);
  console.log(`- Skipped: ${skipped}`);
  console.log(`- Total: ${attractionsData.length}`);
  
  // Count by zone
  const zoneACounts = attractionsData.filter(a => a.zone === 'A').length;
  const zoneBCounts = attractionsData.filter(a => a.zone === 'B').length;
  const zoneCCounts = attractionsData.filter(a => a.zone === 'C').length;
  
  console.log('\n🗺️  By Zone:');
  console.log(`- Zone A (City Center): ${zoneACounts} attractions`);
  console.log(`- Zone B (Suburban): ${zoneBCounts} attractions`);
  console.log(`- Zone C (Regional): ${zoneCCounts} attractions`);
}

seedAttractions()
  .catch((e) => {
    console.error('❌ Error seeding attractions:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
